framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
              format: json
              context: { }
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: '%env(MESSENGER_TRANSPORT_FAILURE)%'
            # sync: 'sync://'
            async_clients_high:
               dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
               serializer: messenger.transport.symfony_serializer
               options:
                   vhost: '%env(MESSENGER_TRANSPORT_VHOST)%'
                   exchange:
                     name: high
                   queues:
                     recharge_mobile_send:
                       binding_keys: [ recharge_mobile_send ]
               retry_strategy:
                   max_retries: 5
                   delay: 1000
                   multiplier: 3

            async_check_status:
               dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
               serializer: messenger.transport.symfony_serializer
               options:
                   vhost: '%env(MESSENGER_TRANSPORT_VHOST)%'
                   exchange:
                     name: low
                   queues:
                      check_status_recharge:
                        binding_keys: [ check_status_recharge ]
               retry_strategy:
                   max_retries: 5
                   delay: 10000
                   multiplier: 2
        routing:
            # Route your messages to the transports
             'App\Message\SaleRechargeMessage': async_clients_high
             'App\Message\CheckSaleMessage': async_check_status

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
