framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
              format: json
              context: { }
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: '%env(MESSENGER_TRANSPORT_FAILURE)%'
            # sync: 'sync://'
            async_notifications_high:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              serializer: messenger.transport.symfony_serializer
              options:
                  vhost: '%env(MESSENGER_TRANSPORT_VHOST)%'
                  exchange:
                    name: high
                  queues:
                    notifications_send_emails:
                      binding_keys: [ notifications_send_emails ]
              retry_strategy:
                  max_retries: 2
                  delay: 1000
                  multiplier: 3
            async_clients_high:
               dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
               serializer: messenger.transport.symfony_serializer
               options:
                   vhost: '%env(MESSENGER_TRANSPORT_VHOST)%'
                   exchange:
                     name: high
                   queues:
                     recharge_mobile_send:
                       binding_keys: [ recharge_mobile_send ]
               retry_strategy:
                   max_retries: 5
                   delay: 1000
                   multiplier: 3

            async_send_sale_package:
               dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
               serializer: messenger.transport.symfony_serializer
               options:
                   vhost: '%env(MESSENGER_TRANSPORT_VHOST)%'
                   exchange:
                     name: highest
                   queues:
                     send_sale_package:
                        binding_keys: [ send_sale_package ]
               retry_strategy:
                   max_retries: 5
                   delay: 1000
                   multiplier: 3

            async_check_status:
               dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
               serializer: messenger.transport.symfony_serializer
               options:
                   vhost: '%env(MESSENGER_TRANSPORT_VHOST)%'
                   exchange:
                     name: highest
                   queues:
                      check_status_recharge:
                        binding_keys: [ check_status_recharge ]
               retry_strategy:
                   max_retries: 5
                   delay: 120000
                   multiplier: 2

            async_send_notification:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              serializer: messenger.transport.symfony_serializer
              options:
                   vhost: '%env(MESSENGER_TRANSPORT_VHOST)%'
                   exchange:
                     name: medium
                   queues:
                     send_balance_notification:
                       binding_keys: [ send_balance_notification ]
              retry_strategy:
                  max_retries: 1
                  delay: 1000
                  multiplier: 2
        routing:
            # Route your messages to the transports
             'App\Message\SaleRechargeMessage': async_clients_high
             'App\Message\CheckSaleMessage': async_check_status
             'App\Message\BalanceMessage': async_send_notification
             'App\Message\SalePackageMessage': async_send_sale_package
             'App\Message\ForgotPasswordMessage': async_notifications_high

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
