apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: api-transferencias
    newName: registry.example.com/api-transferencias
    newTag: latest
  - name: api-transferencias-nginx
    newName: registry.example.com/api-transferencias-nginx
    newTag: latest

patches:
  - path: hpa-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: api-transferencias

  # Scale critical workers in production
  - target:
      kind: Deployment
      name: worker-clients
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2

  - target:
      kind: Deployment
      name: worker-packages
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
