[PHP]
memory_limit = 256M
upload_max_filesize = 10M
post_max_size = 12M

[opcache]
opcache.enable = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
opcache.interned_strings_buffer = 16
opcache.jit = 1255
opcache.jit_buffer_size = 64M

[realpath_cache]
realpath_cache_size = 4096K
realpath_cache_ttl = 600

[apcu]
apc.enabled = 1
apc.shm_size = 64M
