apiVersion: v1
kind: ConfigMap
metadata:
  name: api-transferencias-config
  namespace: api-transferencias
data:
  APP_ENV: "prod"
  APP_DEBUG: "0"
  CORS_ALLOW_ORIGIN: "'^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$'"
  MESSENGER_TRANSPORT_VHOST: "client-vh1"
  MESSENGER_TRANSPORT_FAILURE: "doctrine://default?queue_name=failed"
  JWT_TIMEOUT: "30"
  APP_MAILER_FROM: "soporte@comremit.com"
  MICROSOFT_URL: "https://login.microsoftonline.com"
