apiVersion: v1
kind: Secret
metadata:
  name: api-transferencias-secret
  namespace: api-transferencias
type: Opaque
stringData:
  APP_SECRET: "CHANGE_ME"
  DATABASE_URL: "postgresql://user:password@db-host:5432/app?serverVersion=15&charset=utf8"
  MESSENGER_TRANSPORT_DSN: "amqp://user:password@rabbitmq-host:5672/%2f/"
  MAILER_DSN: "smtps://user:password@smtp-host:465"
  JWT_MEMORY_KEY: "CHANGE_ME"
  JWT_PHRASE_KEY: "CHANGE_ME"
  APP_TEST_PHONE: "0000000000"
