apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Reduce API replicas to 1 for dev
  - target:
      kind: Deployment
      name: api-transferencias
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  # Reduce HPA for dev
  - target:
      kind: HorizontalPodAutoscaler
      name: api-transferencias
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3

  # Set dev environment in configmap
  - target:
      kind: ConfigMap
      name: api-transferencias-config
    patch: |
      - op: replace
        path: /data/APP_ENV
        value: "dev"
      - op: replace
        path: /data/APP_DEBUG
        value: "1"

  # Lower resource limits for dev
  - target:
      kind: Deployment
      name: api-transferencias
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
